import os
import sys
import stat
import subprocess
from pathlib import Path
from loguru import logger

from preflight.config.paths import GLOBAL_HOOKS_DIR

def _get_python_path() -> str:
    """
    Get the absolute path to the current Python executable.
    Formats it safely for a POSIX sh script (Git Bash on Windows requires forward slashes).
    """
    return sys.executable.replace("\\", "/")

def get_hook_script() -> str:
    """
    Generates the POSIX sh script for the Git Pre-Push Hook.
    This script forwards Git's stdin (which contains the branch refs) to our Python CLI.
    """
    python_exe = _get_python_path()
    
    return f"""#!/bin/sh
# ==============================================================================
# Pre-Flight AI - Global Pre-Push Hook Shim
# Automatically generated by 'preflight setup'. Do not edit manually.
# ==============================================================================

# 1. Chain to local repository hook if it exists (e.g., Husky)
# This ensures we do not break existing developer workflows.
LOCAL_HOOK=".git/hooks/pre-push"
if [ -f "$LOCAL_HOOK" ] && [ -x "$LOCAL_HOOK" ]; then
    # Pass stdin (refs) and arguments to the local hook
    "$LOCAL_HOOK" "$@" <&0
    LOCAL_EXIT=$?
    if [ $LOCAL_EXIT -ne 0 ]; then
        exit $LOCAL_EXIT
    fi
fi

# 2. Check if Pre-Flight AI is explicitly disabled for this specific repository
# (Developers can run 'preflight disable' to set this Git config)
DISABLED=$(git config --local preflight.enabled)
if [ "$DISABLED" = "false" ]; then
    exit 0
fi

# 3. Execute Pre-Flight AI Analysis Engine
# We use the absolute Python path to ensure we hit the correct virtual environment.
"{python_exe}" -m preflight.cli.main hook-run "$@" <&0
"""

def install_global_hook():
    """
    Writes the hook script to the global hooks directory and configures Git.
    """
    hook_path = GLOBAL_HOOKS_DIR / "pre-push"
    
    logger.info(f"Writing global pre-push hook shim to {hook_path}")
    
    # Write the script
    with open(hook_path, "w", newline="\n", encoding="utf-8") as f:
        f.write(get_hook_script())
        
    # Make the script executable (chmod +x)
    st = os.stat(hook_path)
    os.chmod(hook_path, st.st_mode | stat.S_IEXEC)
    
    # Format path for git config (ensure forward slashes for Windows compatibility)
    git_hooks_path = str(GLOBAL_HOOKS_DIR).replace("\\", "/")
    
    # Configure Git to use this global directory
    logger.info("Configuring Git global core.hooksPath...")
    try:
        subprocess.run(
            ["git", "config", "--global", "core.hooksPath", git_hooks_path],
            check=True,
            capture_output=True
        )
    except subprocess.CalledProcessError as e:
        logger.error(f"Failed to set Git config: {e.stderr.decode()}")
        raise RuntimeError("Failed to configure git core.hooksPath") from e

def uninstall_global_hook():
    """
    Removes the Pre-Flight AI hook and unsets the Git configuration.
    """
    hook_path = GLOBAL_HOOKS_DIR / "pre-push"
    
    if hook_path.exists():
        hook_path.unlink()
        logger.info("Deleted global pre-push hook shim.")
        
    try:
        subprocess.run(
            ["git", "config", "--global", "--unset", "core.hooksPath"],
            check=True,
            capture_output=True
        )
        logger.info("Unset Git global core.hooksPath.")
    except subprocess.CalledProcessError:
        # It's okay if it wasn't set
        pass